// <auto-generated />
namespace amigopet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedatabase6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedatabase6));
        
        string IMigrationMetadata.Id
        {
            get { return "202103060437486_update-database6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
